[package]
name = "sqlsense"
version = "0.1.0"
authors = [ "Stephen OBrien <wayofthepie@gmail.com>" ]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
dot = "0.1.4"
sqlparser = "0.8.0"
